routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');


Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

app/Licencia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Licencia extends Model
{
    
    protected $fillable = [
        'nombre_programa', 'digitos', 'version','subversion',
     ];
}

app/Http/Controllers/LicenciaController.php
<?php

namespace App\Http\Controllers;

use App\Licencia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Auth; 


class LicenciaController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $licencias=Licencia::paginate(10);
        return view('licencia.licencias',compact('licencias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $licencias=Licencia::create([
            'nombre_programa' => $request['nombre_programa'],
            'digitos' => $request['digitos'],
            'version' => $request['version'],
            'subversion' => $request['subversion'],
           
    ]);
   
    return redirect()->route('altalicencias.index')->with('Success','Elementos guardados'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Licencia  $licencia
     * @return \Illuminate\Http\Response
     */
    public function show(Licencia $licencia)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Licencia  $licencia
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $licencias=Licencia::findOrFail($id);
        return view('licencia/edit',compact('licencias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Licencia  $licencia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $licencias=Licencia::findOrFail($id);
        $licencias->nombre_programa=$request->nombre_programa;
        $licencias->digitos=$request->digitos;
        $licencias->version=$request->version;
        $licencias->subversion=$request->subversion;
        $licencias->save();
        return redirect('altalicencias');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Licencia  $licencia
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Licencia::destroy($id);
        return redirect('altalicencias');
    }
}

resources/views/licencia/edit.blade.php
@extends('licenciass')
 @include('layouts.navbar')
@include('layouts.sidebarAdmin') 
@section('solicitudes-tabla')

                    <h5 class="modal-title text-center" id="exampleModalLabel"> EDITAR INFORMACIÓN </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ url('/altalicencias/'.$licencias->id)}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="modal-body">
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="nombre_programa"> Nombre del programa: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="nombre_programa" name="nombre_programa" value="{{$licencias->nombre_programa}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="digitos">Ultimos 5 digitos de la Licencia:</label>
                            </div>
                            <div class="col-9">
                                <input required required class="form-control" id="digitos" name="digitos" value="{{$licencias->digitos}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="version">Versión: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="version"  name="version" value="{{$licencias->version}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="subversion"> Subversión (Solo si aplica): </label>
                            </div>
                            <div class="col-9">
                                <input  class="form-control" id="subversion" name="subversion" value="{{$licencias->subversion}}">
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endsection

resources/views/licencia/licencias.blade.php
@extends('licenciass')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')


@section('solicitudes-tabla')

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Listado de licencias
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>

                        <th> Nombre del programa </th>
                        <th> Licencia Digitos</th>
                        <th> Versión del Programa</th>
                        <th> Subversión </th>
                        <th> Opciones </th>
                        <th></th>
                    </tr>
                </thead>
               <tbody>
               @foreach($licencias as $licencia)
                   <tr>
                    <td>{{ $licencia ->nombre_programa }}</td>
                    <td>{{ $licencia ->digitos}}</td>
                    <td>{{ $licencia->version }}</td>
                    <td>{{ $licencia->subversion }}</td>
                    <td> <a class="btn btn-warning" href="{{url('/altalicencias/'.$licencia->id.'/edit')}}" class="secondary-content"><i class="fa fa-edit"></i></a></a></td>
                    <td>
                         <form method="post" action="{{url('/altalicencias/'.$licencia->id)}}">
                               {{csrf_field()}}
                               {{method_field('DELETE')}}

                               <button   class="btn btn-danger" type="submit" onclick="return confirm('¿Borrar?');"><i class="fa fa-trash"></i></button>                 
                           </form>
                    </td>
                   </tr>
               @endforeach
               </tbody>
           </table>
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
@endsection



@section('modalregistro')
<div class="modal fade" id="modalregistro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title text-center" id="exampleModalLabel"> AGREGAR LICENCIA </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>


            <form action="{{route('altalicencias.store')}}" method="post" >
                {{csrf_field()}}
                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="nombre_programa"> Nombre del programa: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="nombre_programa" name="nombre_programa" required="">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-3">
                            <label for="digitos"> Ultimos 5 digitos de la Licencia: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="digitos" name="digitos" required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="version"> Versión: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="version" name="version" required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="subversion"> Subversión (Solo si aplica): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="subversion" name="subversion" >
                        </div>
                    </div>
             
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </>
        </form>
    </div>
</div>
</div>
@endsection