routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');


Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

resources/views/admin/agregaCategoria.blade.php
@extends('categoria')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@include('layouts.app')

@section('categoria-tabla')
<div id="listar"></div>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Agregar categoría
    </div>
    <div class="card-body">
        <div class="table-responsive">
                <script type="text/javascript" src="../../../public/js/jquery-3.4.1.min.js"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

                <?php echo '<form action="categoria/store" method="post">' ?>
                @csrf
                <div class="modal-body center">
                    <div class="row form-group">
                        <div class="col-12">
                            <input type="text" name="id"  id="id" hidden="">
                            <label for="solicitante">Categoria:</p>
                        </div>
                        <div class="col-12">
                            <input type="text" class="form-control" name="categoria" id="categoria"  required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-12">
                            <label for="solicitante">Descripcion:</p>
                        </div>
                        <div class="col-12">
                            <textarea type="text" class="form-control" name="descripcion" id="descripcion" required=""></textarea>
                        </div>
                    </div>
                   
                </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </div>
        </form>
                  



</table>
</div>
</div>
<div class="card-footer small text-muted">Actualizado ayer a las 11:59 PM</div>
</div>
@endsection




@section('top')
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
@endsection

resources/views/admin/categorias.blade.php
@extends('categoria')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@section('categoria-tabla')
@include('layouts.app')

<div id="listar"></div>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Categorias
    </div>
    <div class="card-body">
        <div class="table-responsive">
           <div class="text-right"><form action="agregarCategoria"><button type="submit" class="btn btn-primary"> Nueva categoría </button></form> </div><br>
                <script type="text/javascript" src="../../../public/js/jquery-3.4.1.min.js"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th> Categoria </th>
                        <th> Descripcion </th>
                        <th> Opciones </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th> Categoria </th>
                        <th> Descripcion </th>
                        <th> Opciones </th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php

                    foreach ($categorias as $categoria) {
                        echo "<tr>";

                        
                        echo "<td>".$categoria->categoriaReporte."</td>";
                        echo "<td>".$categoria->descripcion."</td>";
                       
                        echo "<td>";                        
                        echo '<form action="categoria/findCategoria" method="post" style="display:inline-block;"> ';
                        ?> @csrf 
                        <input type="text" name="id" value="{{$categoria->id}}" hidden>
                        <?php
                        echo   '<button type="submit" class="btn btn-warning" style="position:relative; left:75%; width: 40px; ">
                                <i class="fa fa-edit"></i>
                              </button> </form>';
                        echo '<button data-toggle="modal" data-target="#modaleliminar" data-id="'.$categoria->id.'" class="btn btn-danger"  style=" position:relative; width: 40px; left:35%;">
                                <i class="fa fa-trash  data-toggle="modal" data-target="#modaleliminar" data-id="'.$categoria->id.'"  ></i>
                              </button>';
                        echo "</td>";
                        echo "</tr>";
                        
                    }
                    ?>
                    <script type="text/javascript">
                        var ATTRIBUTES = ['id'];
                        
                     $('[data-toggle="modal"]').on('click', function (e) {

                      // convert target (e.g. the button) to jquery object
                      var $target = $(e.target);
                      // modal targeted by the button
                      var modalSelector = $target.data('target');
                      
                      // iterate over each possible data-* attribute
                      var i=0;
                      ATTRIBUTES.forEach(function (attributeName) {
                        // retrieve the dom element corresponding to current attribute
                        var $modalAttribute = $(modalSelector + ' #modal-' + attributeName);
                        var dataValue = $target.data(attributeName);
                        // if the attribute value is empty, $target.data() will return undefined.
                        // In JS boolean expressions return operands and are not coerced into
                        // booleans. That way is dataValue is undefined, the left part of the following
                        // Boolean expression evaluate to false and the empty string will be returned
                        $modalAttribute.text(dataValue || '');
                        if (dataValue==null) {
                            dataValue="";
                        }
                            document.getElementById(ATTRIBUTES[i]).value =dataValue;
                            
                            i++;
                    });
                    });
                    </script>


</tbody>
</table>
</div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
@endsection


@section('modaleliminar')
<div class="modal fade" id="modaleliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title text-center" id="exampleModalLabel"> ELIMINAR CATEGORIA </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="categoria/delete" method="POST">    
                @csrf
                <div class="modal-body">
                    <label>¿Desea eliminar la categoría?</label>
                </div>
                
                <input type="text"  name="id"  id="id" hidden>
                <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Eliminar </button>
            </div>
        </form>
    </div>
</div>
</div>
@endsection

@section('top')
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
@endsection

resources/views/admin/edit.blade.php
@extends('usuarios')
@include('layouts.app')

@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@section('content')

                    <h5 class="modal-title text-center" id="exampleModalLabel"> EDITAR INFORMACIÓN </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                </br>
                <form action="{{ url('/usuarios/'.$user->id)}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="modal-body">
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="name"> Nombre: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="name" name="name" value="{{$user->name}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="apellidoP"> Apellido Paterno: </label>
                            </div>
                            <div class="col-9">
                                <input required required class="form-control" id="apellidoP" name="apellidoP" value="{{$user->apellidoP}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="apellidoM">Apellido Materno: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="apellidoM"  name="apellidoM" value="{{$user->apellidoM}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="email"> Correo: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="email" name="email" value="{{$user->email}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="edificio"> Edificio: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="edificio" name="edificio" value="{{$user->edificio}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="departamento"> Departamento: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="departamento" name="departamento" value="{{$user->departamento}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="extensión"> Extensión: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="extensión" name="extension" value="{{$user->extension}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="tipo"> Tipo: </label>
                            </div>
                            <div class="col-9">
                                <select class="form-control" id="tipo" name="idRol" value="3" selected="4">
                                    <?php

                                        foreach ($roles as $rol) {
                                            if ($rol->id==$usuarioRol[0]->idRol) {
                                                echo '<option selected value="'.$rol->id.'">'.$rol->rol.' </option>';                
                                            }else{
                                                echo '<option value="'.$rol->id.'">'.$rol->rol.' </option>';                
                                            }
                                        }
                                    ?>
                                
                                    <!-- <option value="5"> Usuario </option>
                                    <option value="2"> HelpDesk </option>
                                    <option value="3"> Agente 1° Nivel </option>
                                    <option value="4"> Agente 2° Nivel </option> -->
                                    
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/editarCategoria.blade.php
@extends('categoria')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@include('layouts.app')


@section('categoria-tabla')
<div id="listar"></div>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Agregar categoría
    </div>
    <div class="card-body">
        <div class="table-responsive">
                <script type="text/javascript" src="../../../public/js/jquery-3.4.1.min.js"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

                <?php echo '<form action="update" method="post">' ?>
                @csrf
                <div class="modal-body center">
                    <div class="row form-group">
                        <div class="col-12">
                            <input type="text" name="id"  id="id" value="{{$categoria[0]->id}}" hidden="">
                            <label for="solicitante">Categoria:</p>
                        </div>
                        <div class="col-12">
                            <input type="text" class="form-control" name="categoria" id="categoria" value="{{$categoria[0]->categoriaReporte}}" >
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-12">
                            <label for="solicitante">Descripcion:</p>
                        </div>
                        <div class="col-12">
                            <textarea type="text" class="form-control" name="descripcion" id="descripcion" > {{$categoria[0]->descripcion}}</textarea>
                        </div>
                    </div>
                   
                </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </div>
        </form>
                  



</table>
</div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
@endsection



@section('top')
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
@endsection

resources/views/admin/pdf.blade.php
@extends('pdf')

@section('tabla')
    <div class="content">
        <h1 class="display-5 text-center" >REPORTE DE TICKETS</h1>
    </div>
    <div class="content">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Título</th>
                    <th scope="col">Solicitante</th>
                    <th scope="col">Edificio</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Estado</th>
                </tr>
            </thead>
            <tbody>
            @foreach($tickets as $ticket)
                <tr>
                    <th scope="row">{{$ticket->titulo}}</td>
                    <td>{{$ticket->name}}</td>
                    <td>{{$ticket->edificio}}</td>
                    <td>{{$ticket->departamento}}</td>
                    <td>{{$ticket->categoriaReporte}}</td>
                    <td>{{$ticket->estatus}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/pdfSolicitud.blade.php
@extends('pdf')

@section('tabla')    
<title>Solicitud de mantenimiento</title>
<img src="{{asset('bg1.png')}}" width="127%;" style="position: absolute; left: -5rem; top: -5rem;">
<div style="position: absolute; top: 7.4rem; left: 8.5rem; z-index: 2">
	<p>{{$ticket[0]->fechaRecepcion}}</p>
</div>
<div style="position: absolute; top: 7.4rem; left: 34rem; z-index: 2">
	<p>{{$ticket[0]->folioTicket}}</p>
</div>
<div style="position: absolute; top: 9.4rem; left: 12.5rem; z-index: 2">
	<p>{{$solicitante[0]->departamento}}</p>
</div>
<?php
switch ($ticket[0]->idCategoriaReporte) {
	case '1':
		# Hardware...
		echo '<div style="position: absolute; top: 16.0rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
	case '2':
		# Software...
		echo '<div style="position: absolute; top: 17.0rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
	case '8':
		# Telefonia...
		echo '<div style="position: absolute; top: 18.0rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
	case '9':
		# Redes...
		echo '<div style="position: absolute; top: 20.0rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
	case '10':
		# Internet...
		echo '<div style="position: absolute; top: 19.0rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
	default:
		# Otros
		echo '<div style="position: absolute; top: 21.1rem; left: 39.5rem; z-index: 2">
				<p>x</p>
			</div>';		
		break;
}
?>
<div style="position: absolute; top: 25.8rem; left: 3.0rem; z-index: 2">
	<p>{{$ticket[0]->titulo}}</p>
</div>

<div style="position: absolute; top: 34.0rem; left: 3.0rem; z-index: 2">
	<p>{{$ticket[0]->servicioRealizado}}</p>
</div>
<div style="position: absolute; top: 41.5rem; left: 3.0rem; z-index: 2">
	<p>{{$ticket[0]->materialUtilizado}}</p>
</div>
<div style="position: absolute; top: 51.0rem; left: 2.8rem; z-index: 2">
	<p style="font-size: smaller;">{{$solicitante[0]->name}} {{$solicitante[0]->apellidoP}} {{$solicitante[0]->apellidoM}}</p>
</div>
<div style="position: absolute; top: 51.0rem; left: 15.5rem; z-index: 2">
	<p style="font-size: smaller;">{{$user[0]->name}} {{$user[0]->apellidoP}} {{$user[0]->apellidoM}}</p>
</div>

<br><br><br><br><br><br><br><br><br><br>

@endsection

resources/views/admin/reporteFinal.blade.php
@extends('reporteFinal')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@section('reporteFinal')

                    <h5 class="modal-title text-center" id="exampleModalLabel"> REPORTE FINAL</h5>
                    
                </div>
                </br>
                <form action="{{url('/reporte/update')}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                    <input id="id" name="id" value="{{$reporte[0]->id}}" hidden>
                    <div class="modal-body">
                        <div class="row form-group">
                            <div class="col-6">
                                <label for="name">  Descripción del servicio que solicita o falla a reparar </label>
                            </div>
                            <div class="col-12">
                                <textarea class="form-control" id="titulo" name="titulo" required>{{$reporte[0]->titulo}}</textarea>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-6">
                                <label for="apellidoP"> Trabajo o servicio realizado</label>
                            </div>
                            <div class="col-12">
                                <textarea class="form-control" id="servicioRealizado" name="servicioRealizado" required >{{$reporte[0]->servicioRealizado}}</textarea>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-6">
                                <label for="apellidoP"> Material utilizado</label>
                            </div>
                            <div class="col-12">
                                <textarea class="form-control" id="materialUtilizado" name="materialUtilizado" >{{$reporte[0]->materialUtilizado}}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/reportes.blade.php
@extends('reportes')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')

@section('form')
    <div class="text-center">
        <h1> NUEVO REPORTE </h1>
    </div>
    <form action="{{action('TicketController@crearReporte')}}" method="POST" target="_blank">
        {{csrf_field()}}      
        <!-- <div class="form-group">
          <label for="exampleFormControlSelect1"> Tipo de reporte: </label>
          <select class="form-control" id="selecTipo" name="selecTipo"  required >
            <option value='0'> General </option>
            <option value='1'> Por fecha </option>
          </select>
        </div>               -->
        <div class="form-group">
          <label for="exampleFormControlSelect1" name="labelini" id="labelini" > Fecha inicial: </label>
          <input  type="date" class="form-control" name="fechaini" id="fechaini" required >
        </div>      
        <div class="form-group">
          <label for="exampleFormControlSelect1"  name="labelfin" id="labelfin" > Fecha final: </label>
          <input  type="date" class="form-control" name="fechafin" id="fechafin" required >
        </div>
        <input type="text" name="x" id="x" hidden>        
        <!-- <input  type="date" class="form-control" name="fechaactual" id="fechaactual" hidden > -->
        <div class="form-group">
            <button type="submit" id="boton" name="boton" class="btn btn-primary mb-2" style="width: 100%;"> Generar </button>
        </div>

    </form>
@endsection

resources/views/admin/ticket.blade.php
@extends('ticket')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')

@section('solicitud')
    <div class="text-center">
        <h1> NUEVO TICKET </h1>
    </div>
    <form method="POST" action="{{route('tickets.store')}}">
        {{csrf_field()}}
        <div class="form-group">
          <label for="exampleFormControlSelect1"> Equipo a Reportar: </label>
          <select class="form-control" id="selectEquipo" name="selectEquipo" onchange="" required >
            <option value="Teléfono"> Teléfono </option>
            <option value="Impresora"> Impresora </option>
            <option value="Laptop / PC"> Laptop / PC </option>
            <option value="Otro"> Otro </option>
          </select>
        </div>
        <div class="form-group">            
          <input type="text" placeholder="Otro" class="form-control" id="inputEquipo" name="inputEquipo" value=" " required hidden=""  />
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Tipo de Reporte: </label>
            <select class="form-control" id="selectTipoReporte" name="selectTipoReporte" onchange="" required>
                <option value="1"> Falla </option>
                <option value="3"> Solicitud </option>
                <option value="2"> Actividad </option>
                <option value="4"> Otro </option>
            </select>
        </div>
        <div class="form-group">            
          <input type="text" placeholder="Otro" class="form-control" id="inputtipoReporte" name="inputtipoReporte" value=" " required hidden="" />
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Categoria de reporte: </label>
            <select class="form-control" id="selectCategoria" name="selectCategoria"  onchange="" required>
            <?php
            foreach ($categorias as $categoria) {
                echo "<option value='".$categoria->id."'>".$categoria->categoriaReporte."</option>";
            }
            ?>
            </select>
        </div>
        
        
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Nivel de Urgencia: </label>
            <select class="form-control" id="selectUrgencia" name="selectUrgencia"  onchange="otro()" required>
                <option value="4"> Bajo </option>
                <option value="3" selected > Medio </option>
                <option value="2"> Alto </option>
                <option value="1"> Urgente </option>
            </select>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1" id="labelUrgencia"> Explique la urgencia </label>
          <textarea class="form-control"  rows="3" name="textUrgencia" id="textUrgencia" required> </textarea>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1"> Ingrese los detalles del reporte </label>
          <textarea class="form-control" id="exampleFormControlTextarea1" name="detalles" rows="3" required></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary mb-2" style="width: 100%;"> Enviar </button>
        </div>
    </form>
@endsection

@section('top')
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
@endsection